[build]
  command = "npm run build"
  publish = "build"

# start.airnote.live is a simple redirect to the airnote.live quickstart 
[[redirects]]
  from = "http://start.chasevantoll.com"
  to = "https://dev.blues.io/datasheets/airnote/airnote-quickstart/"
  force = true