# Infrastructure as Code
services:
  - type: web
    name: airnote.live
    env: static
    domains:
      - airnote.live # see https://render.com/docs/custom-domains
    autoDeploy: true
    buildCommand: npm run build
    staticPublishPath: public
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NOTEHUB_API_URL
        value: https://api.notefile.net
    routes:
      - type: rewrite # Because we're a Single Page App (i.e. uses Client-Side Routing)
        source: /* # every page on the site...
        destination: /index.html # is handled by index.html

  # start.airnote.live is just a simple redirect to the airnote.live quickstart.
  - type: web
    name: start.airnote.live
    env: static
    domains:
      - start.airnote.live # see https://render.com/docs/custom-domains
    autoDeploy: true
    buildCommand: "true" # no build needed to serve files verbatim
    staticPublishPath: ./start.airnote.live
    pullRequestPreviewsEnabled: true

  - type: web
    name: airnote-api
    env: node
    buildCommand: cd server && npm install
    startCommand: node server/server.js
    pullRequestPreviewsEnabled: true
    envVars:
      - key: SAFECAST_USERNAME
        sync: false
      - key: SAFECAST_PASSWORD
        sync: false
      - key: PORT
        value: 3001
